### ISSUE TITLE
Amazon Linux 2?

### ISSUE THREAD

**Issue by analytically** [amazonlinux/autotune#4]
Missing docs about if this works with Amazon Linux 2

**Comment by vallishgv** [comment]
Thanks for reporting this issue. 

Autotune as of today works only with Amazon Linux 2.  I agree that this needs to be documented. We will keep this issue open till we fix the documentation.

**Comment by vallishgv** [comment]
Autotune version 1.0.5 README file has been updated to list currently supported distro's.
